// Mocks generated by Mockito 5.4.5 from annotations
// in convertouch/test/domain/repositories/mock/mockito_mock_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:convertouch/domain/constants/constants.dart' as _i10;
import 'package:convertouch/domain/model/conversion_param_set_value_model.dart'
    as _i7;
import 'package:convertouch/domain/model/dynamic_data_model.dart' as _i6;
import 'package:convertouch/domain/model/exception_model.dart' as _i5;
import 'package:convertouch/domain/model/list_value_model.dart' as _i9;
import 'package:convertouch/domain/repositories/network_repository.dart' as _i2;
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockitoNetworkRepository extends _i1.Mock
    implements _i2.NetworkRepository {
  MockitoNetworkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ConvertouchException, _i6.DynamicDataModel?>>
      fetchByParams({required _i7.ConversionParamSetValueModel? params}) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchData,
              [],
              {#params: params},
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.ConvertouchException,
                    _i6.DynamicDataModel?>>.value(_i8.dummyValue<
                _i4.Either<_i5.ConvertouchException, _i6.DynamicDataModel?>>(
              this,
              Invocation.method(
                #fetchData,
                [],
                {#params: params},
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.ConvertouchException, _i6.DynamicDataModel?>>);

  @override
  _i3.Future<_i4.Either<_i5.ConvertouchException, List<_i9.ListValueModel>>>
      fetchList({
    required _i10.ConvertouchListType? listType,
    required _i7.ConversionParamSetValueModel? params,
    required int? pageSize,
    required int? pageNum,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchList,
              [],
              {
                #listType: listType,
                #params: params,
                #pageSize: pageSize,
                #pageNum: pageNum,
              },
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.ConvertouchException,
                    List<_i9.ListValueModel>>>.value(_i8.dummyValue<
                _i4.Either<_i5.ConvertouchException, List<_i9.ListValueModel>>>(
              this,
              Invocation.method(
                #fetchList,
                [],
                {
                  #listType: listType,
                  #params: params,
                  #pageSize: pageSize,
                  #pageNum: pageNum,
                },
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.ConvertouchException, List<_i9.ListValueModel>>>);
}
