// Mocks generated by Mockito 5.4.5 from annotations
// in convertouch/test/data/repositories/net/network_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i2;
import 'package:convertouch/data/dao/dynamic_value_dao.dart' as _i10;
import 'package:convertouch/data/dao/net/network_helper/network_helper.dart'
    as _i3;
import 'package:convertouch/data/dao/network_dao.dart' as _i5;
import 'package:convertouch/data/dao/unit_dao.dart' as _i7;
import 'package:convertouch/data/entities/dynamic_value_entity.dart' as _i11;
import 'package:convertouch/data/entities/unit_entity.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConnectivity_0 extends _i1.SmartFake implements _i2.Connectivity {
  _FakeConnectivity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHelper extends _i1.Mock implements _i3.NetworkHelper {
  MockNetworkHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Connectivity get connectivity => (super.noSuchMethod(
        Invocation.getter(#connectivity),
        returnValue: _FakeConnectivity_0(
          this,
          Invocation.getter(#connectivity),
        ),
      ) as _i2.Connectivity);

  @override
  _i4.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [NetworkDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkDao extends _i1.Mock implements _i5.NetworkDao {
  MockNetworkDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> fetch(
    String? urlPath, {
    Map<String, dynamic>? queryParams,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [urlPath],
          {
            #queryParams: queryParams,
            #headers: headers,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #fetch,
            [urlPath],
            {
              #queryParams: queryParams,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [UnitDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitDao extends _i1.Mock implements _i7.UnitDao {
  MockUnitDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.UnitEntity>> getByParamId({
    required int? paramId,
    required int? pageSize,
    required int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByParamId,
          [],
          {
            #paramId: paramId,
            #pageSize: pageSize,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<List<_i8.UnitEntity>> searchWithGroupId({
    required String? searchString,
    required int? unitGroupId,
    required int? pageSize,
    required int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchWithGroupId,
          [],
          {
            #searchString: searchString,
            #unitGroupId: unitGroupId,
            #pageSize: pageSize,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<List<_i8.UnitEntity>> searchWithParamIdAndPossibleUnits({
    required String? searchString,
    required int? paramId,
    required int? pageSize,
    required int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchWithParamIdAndPossibleUnits,
          [],
          {
            #searchString: searchString,
            #paramId: paramId,
            #pageSize: pageSize,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<List<_i8.UnitEntity>> searchWithParamId({
    required String? searchString,
    required int? paramId,
    required int? pageSize,
    required int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchWithParamId,
          [],
          {
            #searchString: searchString,
            #paramId: paramId,
            #pageSize: pageSize,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<_i8.UnitEntity?> getByCode(
    int? unitGroupId,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCode,
          [
            unitGroupId,
            code,
          ],
        ),
        returnValue: _i4.Future<_i8.UnitEntity?>.value(),
      ) as _i4.Future<_i8.UnitEntity?>);

  @override
  _i4.Future<List<_i8.UnitEntity>> getBaseUnits(int? unitGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBaseUnits,
          [unitGroupId],
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<_i8.UnitEntity?> getUnit(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getUnit,
          [id],
        ),
        returnValue: _i4.Future<_i8.UnitEntity?>.value(),
      ) as _i4.Future<_i8.UnitEntity?>);

  @override
  _i4.Future<List<_i8.UnitEntity>> getUnitsByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitsByIds,
          [ids],
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<List<_i8.UnitEntity>> getUnitsByCodes(
    int? groupId,
    List<String>? codes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitsByCodes,
          [
            groupId,
            codes,
          ],
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<List<_i8.UnitEntity>> updateUnitsCoefficients(
    _i9.Database? db,
    int? groupId,
    Map<String, double?>? codeToCoefficient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUnitsCoefficients,
          [
            db,
            groupId,
            codeToCoefficient,
          ],
        ),
        returnValue: _i4.Future<List<_i8.UnitEntity>>.value(<_i8.UnitEntity>[]),
      ) as _i4.Future<List<_i8.UnitEntity>>);

  @override
  _i4.Future<int> insert(_i8.UnitEntity? unit) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [unit],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateBatch(
    _i9.Database? db,
    List<_i8.UnitEntity>? units,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [
            db,
            units,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> update(_i8.UnitEntity? unit) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [unit],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> remove(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [ids],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DynamicValueDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicValueDao extends _i1.Mock implements _i10.DynamicValueDao {
  MockDynamicValueDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.DynamicValueEntity?> get(int? unitId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [unitId],
        ),
        returnValue: _i4.Future<_i11.DynamicValueEntity?>.value(),
      ) as _i4.Future<_i11.DynamicValueEntity?>);

  @override
  _i4.Future<List<_i11.DynamicValueEntity>> getList(List<int>? unitIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [unitIds],
        ),
        returnValue: _i4.Future<List<_i11.DynamicValueEntity>>.value(
            <_i11.DynamicValueEntity>[]),
      ) as _i4.Future<List<_i11.DynamicValueEntity>>);

  @override
  _i4.Future<void> insertBatch(
    _i9.Database? db,
    List<_i11.DynamicValueEntity>? entities,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertBatch,
          [
            db,
            entities,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBatch(
    _i9.Database? db,
    List<_i11.DynamicValueEntity>? entities,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [
            db,
            entities,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
